[package]
name = "ascii_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = "0.18.0"
colored = "2.1.0"
derive_builder = "0.20.1"
crossterm = "0.28.1"
rand = "0.9.0-alpha.2"
rayon = "1.6"